version: '3.8'

services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  flask-app:
    build:
      context: ./server  # Point to the directory containing the Dockerfile
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - OLLAMA_HOST=http://ollama:11434
      - HF_TOKEN=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
    depends_on:
      - ollama

volumes:
  ollama_data: